<?php
/**
 * Created by PhpStorm.
 * User: tutyo
 * Date: 24.08.2018
 * Time: 18:52
 */

namespace app\controllers;


use yii\web\Controller;

class MainController extends Controller
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionMain()
    {
        return $this->render('main', []);
    }
}